name: BCNotification

on: issues
  types: [opened, edited, labeled]

jobs:
  send_mail:
     
    runs-on: ubuntu-latest
    
    steps:
      - name: SendGrid
        uses: peter-evans/sendgrid-action@v1.0.0
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
