name: BCNotification
on: 
  issues:
    types: [edited, labeled]
jobs:
  sendGrid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: issue-notifier
        uses: timheuer/issue-notifier@v1
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        with:
          toMailAddress: 'tim@timheuer.com'
          fromMailAddress: 'no-reply@example.com'
          subject: 'test from consumption repo'
          labelsToMonitor: 'breaking-change,big-bug'
